version: "3.9"

services:
  bucket_list:
    build:
      context: ./api/bucket_list
      dockerfile: dockerfile
    container_name: bucket_list_service
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network
   
     

  s3_upload:
    build:
      context: ./api/s3_upload
      dockerfile: dockerfile
    container_name: s3_upload_service
    ports:
      - "5001:5000"
    restart: always
    networks:
      - app-network
    
    

  video_ai:
    build:
      context: ./api/video_ai
      dockerfile: dockerfile
    container_name: video_ai_service
    ports:
      - "5002:5000"
    restart: always
    environment:
      - AWS_REGION=ap-northeast-2
    networks:
      - app-network
    
  sign_upin:
    build:
      context: ./api/sign_upin
      dockerfile: dockerfile
    container_name: sign_upin_service
    ports:
      - "5005:5000"
    restart: always
    environment:
      - COGNITO_USER_POOL_ID=ap-northeast-2_fHq8zuye4
      - COGNITO_CLIENT_ID=4k5u5pgsiis0ariqeqhei7p1hf
      - COGNITO_CLIENT_SECRET=
      - AWS_REGION=ap-northeast-2
    networks:
      - app-network
    

  front_final:
    build:
      context: ./front_final
      dockerfile: Dockerfile
    container_name: front_service
    ports:
      - "5003:5000"
    restart: always
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge
