version: "3.9"

services:
  bucket_list:
    build:
      context: ./api/bucket_list
      dockerfile: dockerfile
    container_name: bucket_list_service
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network
   
     

  s3_upload:
    build:
      context: ./api/s3_upload
      dockerfile: dockerfile
    container_name: s3_upload_service
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network
    
    

  video_ai:
    build:
      context: ./api/video_ai
      dockerfile: dockerfile
    container_name: video_ai_service
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network
    
  front_final:
    build:
      context: ./front_final
      dockerfile: Dockerfile
    container_name: front_service
    ports:
      - "5003:5000"
    restart: always
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge
